Local Bucketing Implementation
DevCycleHQ/go-server-sdk pull request #10
Opened 2022-08-29 20:55 UTC by JamieSinn

Done:
- Sets up local bucketing tests for each of the new functions
- Events callback system for readying and notifications
- Config manager

WIP:
- Cleanup of user exposed properties/functions.

Still needed:
- Event polling impl assuming WASM handles it.
- More tests

2022-09-16 15:02 UTC, jonathannorris requested changes

2022-09-16 15:02 UTC, jonathannorris commented on localbucketing.go
> +	log.Println("Initialized DevCycle LocalBucketing")
cleanup logs?

2022-09-16 15:02 UTC, jonathannorris commented on localbucketing.go
> +	_generateBucketedConfigForUser := d.wasmInstance.GetExport(d.wasmStore, "initEventQueue").Func()
rename `_generateBucketedConfigForUser` as `_initEventQueue`

2022-09-16 15:02 UTC, jonathannorris commented on localbucketing.go
> +	_generateBucketedConfigForUser := d.wasmInstance.GetExport(d.wasmStore, "flushEventQueue").Func()
rename `_generateBucketedConfigForUser`

2022-09-16 15:02 UTC, jonathannorris commented on localbucketing.go
> +	_generateBucketedConfigForUser := d.wasmInstance.GetExport(d.wasmStore, "eventQueueSize").Func()
rename `_generateBucketedConfigForUser`

2022-09-16 15:08 UTC, jonathannorris requested changes

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +			variableEvaluationType = EventType_VariableEvaluated
Where are these defined? can we make sure they are `aggVariableEvaluated` and `aggVariableDefaulted`

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +				return Variable{}, err
We should not return any errors here, we do not want to block a variable for an event-saving issue.

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +		return bucketed.Variables[key], err
Is there a way to ignore all these errors? basically if there is an error we should return a Variable with the default value as a backup, this method shouldn't return any errors.

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +		return user.Variables, err
Same here this probably shouldn't return errors.

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +	event.ClientDate = time.Now()
I don't think this needs to be set here, AS will handle this.

2022-09-16 15:08 UTC, jonathannorris commented on api_devcycle.go
> +	event.Type_ = "customEvent"
I don't think this is correct either. Basically the only param that should be need to be set on the DVCEvent JSON Obj that is sent to AS is `type`: 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/1219069/190671279-3ce575c2-d107-4ca9-b9f6-f07426d5227a.png">

The rest of the types are optional: 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/1219069/190671334-18f4e1ee-f125-4be8-ac24-51422b0edcd5.png">

2022-09-16 15:34 UTC, JamieSinn commented on example/cloud/main.go
> +		DisableCustomEventLogging:    false,
These are used to configure the eventqueueoptions object - but I'll just pass them in and skip checking them in the queue methods.

2022-09-16 15:37 UTC, JamieSinn commented on eventqueue.go
> +				case <-ctx.Done():
application crash, or context is failed. This prevents the app from hanging because there's a background thread running. It's also called to abort polling if there is a non-retryable error.

2022-09-16 15:38 UTC, JamieSinn commented on localbucketing.go
> +	log.Println("Initialized DevCycle LocalBucketing")
C# Has this too - mostly a "things worked" info message
Can remove if not needed.

2022-09-16 15:43 UTC, JamieSinn commented on eventqueue.go
> +	if !e.options.DisableLocalBucketing {
These are checks to prevent null pointers if accessing an unintialized localbucketing object.

2022-09-16 15:43 UTC, JamieSinn commented on eventqueue.go
> +	if !e.options.DisableLocalBucketing && localBucketing != nil {
These are checks to prevent null pointers if accessing an unintialized localbucketing object.

2022-09-20 15:10 UTC, JamieSinn commented on api_devcycle.go
> +				return Variable{}, err
Did a hybrid - returning a default and the error to not break procedure.

2022-09-20 15:11 UTC, JamieSinn commented on api_devcycle.go
> +		return bucketed.Variables[key], err
Logged the error and ignored it.

2022-09-20 15:12 UTC, JamieSinn commented on api_devcycle.go
> +		return user.Variables, err
Returned a default if there was an error - which is just an empty string:variable map. Returning the error is needed still, but not catastrophic since the user can still ignore it.

2022-09-20 15:12 UTC, JamieSinn commented on api_devcycle.go
> +	event.ClientDate = time.Now()
removed.

2022-09-20 15:12 UTC, JamieSinn commented on api_devcycle.go
> +	event.Type_ = "customEvent"
Fixed.

2022-09-21 17:04 UTC, jonathannorris requested changes

2022-09-21 17:04 UTC, jonathannorris commented on configuration.go
> +func (o *DVCOptions) CheckDefaults() {
Check the logic on these because some of them we try and set minumum values like this: 
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1219069/191566684-b2407927-7a63-48ed-87ec-50cedfb6e07d.png">

2022-09-21 17:05 UTC, JamieSinn commented on eventqueue.go
> +	if !e.options.DisableLocalBucketing && localBucketing != nil {
yeah can invert.

2022-09-21 17:06 UTC, JamieSinn commented on api_devcycle.go
> +func (a *DVCClientService) Variable(ctx context.Context, userdata UserData, key string, defaultValue interface{}) (Variable, error) {
We should always be including an error, regardless of whether the variable is a valid return. It's just a golang handler convention.

2022-09-21 17:06 UTC, JamieSinn commented on api_devcycle.go
> +	if event.Type_ == "" {
Type is a reserved keyword, and if started with `_Type` - it would not be an "exported" value from the struct - ie - not accessible outside of the package.

2022-09-21 17:07 UTC, JamieSinn commented on api_devcycle.go
> +func (a *DVCClientService) Track(ctx context.Context, user UserData, event DVCEvent) (InlineResponse201, error) {
It's a generated return type - realistically we can abstract it to a bool.

2022-09-21 17:09 UTC, JamieSinn commented on configmanager.go
> +	return fmt.Sprintf("https://config-cdn.devcycle.com/config/v1/server/%s.json", e.environmentKey)
We can - it's planned but wasn't part of this initial runthrough

2022-09-21 17:49 UTC, jonathannorris commented on model_platformdata.go
> +type PlatformData struct {
can you add hostname to PlatformData, and have it automatically set from the systems hostname.

2022-09-21 17:50 UTC, jonathannorris commented on model_platformdata.go
> +type PlatformData struct {
ie: 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1219069/191575458-80fe10c8-d274-4c9d-921f-3c0b8348bf78.png">

2022-09-22 14:22 UTC, jonathannorris approved these changes

2022-09-22 14:23 UTC, merged