add initial support for managed thread pool
DevCycleHQ/go-server-sdk pull request #102
Opened 2023-03-07 19:17 UTC by ajwootto

2023-03-07 19:17 UTC, ajwootto commented
Current dependencies on/for this PR:
* main
  * **PR #101** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/go-server-sdk/101" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #102** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/go-server-sdk/102" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/DevCycleHQ/go-server-sdk/102?utm_source=stack-comment).

2023-03-08 19:51 UTC, JamieSinn commented on client_test.go
> +			//if i%200 == 1 {
why?

2023-03-08 19:51 UTC, JamieSinn commented on client_test.go
> +			//if i%200 == 1 {
por que?

2023-03-08 19:54 UTC, ajwootto commented on client_test.go
> +			//if i%200 == 1 {
was testing what happened when setting config while threads were busy executing variable calls

2023-03-10 22:26 UTC, JamieSinn commented on configuration.go
> +		o.MaxWasmWorkers = runtime.NumCPU()
This should be GOMAXPROCS

2023-03-15 15:42 UTC, JamieSinn requested changes

2023-03-15 15:42 UTC, JamieSinn commented on client.go
> -	options.CheckDefaults()
is this being removed or moved somewhere else?

2023-03-15 20:21 UTC, JamieSinn approved these changes

2023-03-15 20:29 UTC, chris-hoefgen approved these changes
These look good to me and combined with the load test i'm feeling good about the changes. I would give Rob the final approval as his Go skillz are stronger than me.

2023-03-15 20:49 UTC, rob-odwyer reviewed
Couple of questions, but looks pretty close to ready!

2023-03-15 20:49 UTC, rob-odwyer commented on client.go
> +	}
Have we tested this Close flow anywhere? I don't think we used it in the benchmark(s) at all.

2023-03-15 20:51 UTC, ajwootto commented on client.go
> +			if c.bucketingWorkerPool != nil {
we could consider just always using the pool even when the CPU count is 1? that would eliminate some redundant code paths. I originally did it this way to de-risk adding the thread pooling

2023-03-15 20:51 UTC, ajwootto commented on client.go
> +	}
it's tested by the test harness

2023-03-15 20:51 UTC, ajwootto commented on thread_pool.go
> +	ImHere   bool
forgot to remove 👍

2023-03-15 20:53 UTC, rob-odwyer commented on client.go
> +			if c.bucketingWorkerPool != nil {
That's probably the simplest approach, but I think we can leave it for a later refactor.

2023-03-16 15:10 UTC, merged