Do you even bench
DevCycleHQ/go-server-sdk pull request #108
Opened 2023-03-08 19:43 UTC by JamieSinn

2023-03-08 22:02 UTC, ajwootto commented on bench/benchy.go
> +	client, err := devcycle.NewDVCClient(os.Getenv("DVC_SERVER_KEY"), &devcycle.DVCOptions{})
lets use `DVC_SERVER_SDK_KEY` consistently everywhere

2023-03-08 22:14 UTC, JamieSinn commented on bench/benchy.go
> +	client, err := devcycle.NewDVCClient(os.Getenv("DVC_SERVER_KEY"), &devcycle.DVCOptions{})
will swap - but need to switch this away from a full go module to just a file - it tries to source the public version instead of the local one

2023-03-09 17:04 UTC, ajwootto commented on bench/benchy.go
> +	client, err := devcycle.NewDVCClient(os.Getenv("DVC_SERVER_KEY"), &devcycle.DVCOptions{})
bump

2023-03-09 17:05 UTC, JamieSinn commented on bench/benchy.go
> +	client, err := devcycle.NewDVCClient(os.Getenv("DVC_SERVER_KEY"), &devcycle.DVCOptions{})
right - didn't copy that - sec

2023-03-10 19:17 UTC, ajwootto approved these changes

2023-03-10 19:18 UTC, ajwootto requested changes
dependency question

2023-03-10 19:37 UTC, JamieSinn commented on go.mod
> +	github.com/gin-gonic/gin v1.9.0
Not intended to be merged in this format - we're going to change this to pull from released SDK versions instead.

This version just allows you to do local benching.

2023-03-14 16:38 UTC, closed without merging