feat: OpenFeature provider (DVC-7165)
DevCycleHQ/go-server-sdk pull request #228
Opened 2023-10-23 22:40 UTC by rob-odwyer

Continuation of #175 using a new branch.

2023-10-26 23:51 UTC, rob-odwyer commented on README.md
> +- [The DevCycle Go OpenFeature Provider](https://docs.devcycle.com/sdk/server-side-sdks/go/go-openfeature)
Need to actually create this page before merging this.

2023-10-27 16:34 UTC, chris-hoefgen requested changes

2023-10-27 16:34 UTC, chris-hoefgen commented on openfeature_provider.go
> +	if exists {
I think we should prioritize using the Targeting Key over the UserID in the context as it is supposed to be the standard way to identify the target in the OpenFeature api

2023-10-27 16:34 UTC, chris-hoefgen commented on openfeature_provider.go
> +	if val == nil {
So apparently null is a valid value in custom data for DevCycle, I ended up explicitly adding it in the Java SDK.  I'm wondering if we should triple check that with Jonathan though since I personally think it is weird to have a map with a key that points at null.

2023-10-27 16:34 UTC, chris-hoefgen commented on example/openfeature/main.go
> +	value, err := client.ObjectValue(context.Background(), "test-json-variable", map[string]interface{}{"value": "default"}, evalCtx)
I like showing multiple examples with different data types. I'll have to pull that into the java & python examples as well.

2023-10-27 16:34 UTC, chris-hoefgen commented on testdata/fixture_small_config.json
Might be worth adding another variable that is explicitly a float to make sure those number conversions work as expected

2023-10-27 17:33 UTC, rob-odwyer commented on openfeature_provider.go
> +	if val == nil {
Interesting - that's good to check for sure.
I also wondered whether nil was supposed to be a valid object value to return? I don't think it is currently supported given how the Client handles them (defaults if it's nil).

2023-10-27 17:34 UTC, rob-odwyer commented on testdata/fixture_small_config.json
That's a good call - I'll add that.

2023-10-31 21:59 UTC, Kavindu-Dodan commented on openfeature_provider.go
> +				ResolutionError: openfeature.NewTypeMismatchResolutionError("Variable result is nil"),
I was checking the PR from the OpenFeature point of view and came across this error message. The error message here needs improvement as the `nil` case is already handled. 

Otherwise the responses are compliant with OF :)

2023-11-02 16:26 UTC, JamieSinn commented on client.go
> +
Should we expose this to the public? I guess it's just a helper function for us really?

2023-11-02 16:27 UTC, JamieSinn commented on README.md
> +This SDK provides an implementation of the [OpenFeature](https://openfeature.dev/) Provider interface. Use the `getOpenFeatureProvider()` method on the DevCycle SDK client to obtain a provider for Op
```suggestion
This SDK provides an implementation of the [OpenFeature](https://openfeature.dev/) Provider interface. Use the `OpenFeatureProvider()` method on the DevCycle SDK client to obtain a provider for OpenFeature.
```

2023-11-02 16:28 UTC, JamieSinn commented on client.go
> +
Nevermind - I see it later on.

2023-11-02 16:33 UTC, JamieSinn commented on openfeature_provider.go
> +		if value == nil {
Do we not want to allow setting a custom data property to be null without explicitly calling it out as customdata?

2023-11-02 17:07 UTC, JamieSinn commented on openfeature_provider.go
> +		if value == nil {
ie -https://github.com/DevCycleHQ/dotnet-server-sdk/blob/main/DevCycle.SDK.Server.Common/Model/DevCycleUser.cs#L418C51-L418C51

2023-11-02 18:33 UTC, rob-odwyer commented on openfeature_provider.go
> +		if value == nil {
Good catch on this - I found some other fun bugs in custom data handling that I'm fixing now as well.

2023-11-02 18:34 UTC, JamieSinn commented on openfeature_provider.go
> +		if value == nil {
the handling is weird as heck

2023-11-02 21:14 UTC, rob-odwyer commented on openfeature_provider.go
> +		if value == nil {
@JamieSinn Think I've made it cover everything now, mind taking another look?

2023-11-03 16:47 UTC, JamieSinn approved these changes
I'm liking the testing setup here, might want to copy to the others

2023-11-03 17:49 UTC, merged