feat: update support for passthrough rollouts
DevCycleHQ/go-server-sdk pull request #257
Opened 2024-05-08 17:30 UTC by suthar26

- add new passthrough logic for rollout checking

2024-05-08 17:30 UTC, suthar26 commented
* **#257** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/go-server-sdk/257?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @suthar26 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-08 18:31 UTC, JamieSinn requested changes

2024-05-08 18:31 UTC, JamieSinn commented on api/model_public_project.go
> +	DisablePassthroughRollouts bool `json:"disablePassthroughRollouts" default:"false"`
defaults aren't used this way

2024-05-08 18:31 UTC, JamieSinn commented on api/model_public_project.go
> +	DisablePassthroughRollouts bool `json:"disablePassthroughRollouts" default:"false"`
```suggestion
	DisablePassthroughRollouts bool `json:"disablePassthroughRollouts"` 
```

2024-05-08 18:31 UTC, JamieSinn commented on bucketing/bucketing_test.go
> +	err := json.Unmarshal( test_config, &test_config_json )
run `go fmt`

2024-05-08 18:31 UTC, JamieSinn commented on bucketing/testdata/fixture_test_config.json
> +            "values": ["test@email.com", "test2@email.com"]
this should be in the most expanded format possible

2024-05-08 18:31 UTC, JamieSinn commented on bucketing/testdata/fixture_test_config.json
Make sure all the other test config files are updated to pass this change too.

2024-05-09 14:25 UTC, JamieSinn commented on bucketing/bucketing_test.go
> +	test_config_json["project"].(map[string]interface{})["settings"].(map[string]interface{})["disablePassthroughRollouts"] = true
This should be a separate config that isn't hardcoding the path/value.

2024-05-09 18:41 UTC, JamieSinn commented on bucketing/bucketing_test.go
> +	test_config_json["project"].(map[string]interface{})["settings"].(map[string]interface{})["disablePassthroughRollouts"] = true
or better yet - update all the configs to have a valid setting and ensure that it doesn't break existing tests

2024-05-09 19:23 UTC, JamieSinn approved these changes

2024-05-09 19:38 UTC, jsalaber reviewed
LGTM, but will wait approval from jamie

2024-05-09 19:39 UTC, jsalaber approved these changes

2024-05-09 21:00 UTC, merged