add oninitialized channel that allows the user to make calls before the client is initialized
DevCycleHQ/go-server-sdk pull request #26
Opened 2023-01-18 19:14 UTC by elliotCamblor

How it works:
- The user can choose to pass in an "OnInitializedChannel" into DVCOptions
- If this channel exists then the initialization process will be run in a go routine, meaning client calls can be made before the bucketing lib is initialized
- The user can listen on the channel to block the main process until init is complete
- By not passing in the channel param the sdk will behave the same as it did before

2023-01-18 20:12 UTC, JamieSinn requested changes
No unit tests?

2023-01-18 20:15 UTC, elliotCamblor commented
the whole point of the test harness is so we dont have to write unit tests

2023-01-19 16:47 UTC, JamieSinn approved these changes

2023-01-19 17:06 UTC, ajwootto commented on api_devcycle.go
> +		if a.client.isInitialized {
it would be easier to read if you just early returned here instead

2023-01-19 17:07 UTC, elliotCamblor commented on api_devcycle.go
> +		if a.client.isInitialized {
word

2023-01-19 17:09 UTC, ajwootto commented on client.go
> +	if options.OnInitializedChannel != nil {
does this need to wait until the config is fetched or is that happening implicitly somewhere?

2023-01-19 17:30 UTC, ajwootto commented on example/local/main.go
> +	if <-onInitialized {
do you actually care if the value here is "true", otherwise I don't think you need the if statement you can just wait on the channel directly:
`<-onInitialized`
`log.Printf("client initialized")`

2023-01-19 19:26 UTC, ajwootto commented on api_devcycle.go
> +			return false, errors.New("client not yet initialized")
technically we just log and return on other platforms rather than throwing

2023-01-19 19:32 UTC, ajwootto approved these changes

2023-01-19 19:32 UTC, merged